import type { Metadata } from "next";
import { Figtree, Poppins, PT_Sans } from "next/font/google";
import "./globals.scss";

const figtree = Figtree({
  variable: "--font-figtree",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "900"],
});

const pt_sans = PT_Sans({
  variable: "--font-pt-sans",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${pt_sans.variable} ${poppins.variable} ${figtree.variable}`}
      >
        <div className="">{children}</div>
      </body>
    </html>
  );
}
